/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsNameRouteImport } from './routes/sessions.$name'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNameRoute = SessionsNameRouteImport.update({
  id: '/sessions/$name',
  path: '/sessions/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/health': typeof HealthRoute
  '/monitor': typeof MonitorRoute
  '/personas': typeof PersonasRoute
  '/usage': typeof UsageRoute
  '/sessions/$name': typeof SessionsNameRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/health': typeof HealthRoute
  '/monitor': typeof MonitorRoute
  '/personas': typeof PersonasRoute
  '/usage': typeof UsageRoute
  '/sessions/$name': typeof SessionsNameRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/health': typeof HealthRoute
  '/monitor': typeof MonitorRoute
  '/personas': typeof PersonasRoute
  '/usage': typeof UsageRoute
  '/sessions/$name': typeof SessionsNameRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/health'
    | '/monitor'
    | '/personas'
    | '/usage'
    | '/sessions/$name'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/health'
    | '/monitor'
    | '/personas'
    | '/usage'
    | '/sessions/$name'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/conversations'
    | '/health'
    | '/monitor'
    | '/personas'
    | '/usage'
    | '/sessions/$name'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsRoute: typeof ConversationsRoute
  HealthRoute: typeof HealthRoute
  MonitorRoute: typeof MonitorRoute
  PersonasRoute: typeof PersonasRoute
  UsageRoute: typeof UsageRoute
  SessionsNameRoute: typeof SessionsNameRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$name': {
      id: '/sessions/$name'
      path: '/sessions/$name'
      fullPath: '/sessions/$name'
      preLoaderRoute: typeof SessionsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsRoute: ConversationsRoute,
  HealthRoute: HealthRoute,
  MonitorRoute: MonitorRoute,
  PersonasRoute: PersonasRoute,
  UsageRoute: UsageRoute,
  SessionsNameRoute: SessionsNameRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
