"""add monitor tables

Revision ID: d7d22e4ac66c
Revises: a1b2c3d4e5f6
Create Date: 2026-02-28 22:46:35.918582
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd7d22e4ac66c'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('monitor_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['monitor_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'name', name='uq_topic_entity_name')
    )
    op.create_table('monitor_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['monitor_entities.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['monitor_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('has_changes', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['monitor_entities.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['monitor_resources.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['monitor_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor_subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('channel_config', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['monitor_entities.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['monitor_resources.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['monitor_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor_digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['monitor_entities.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['monitor_resources.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['monitor_snapshots.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['monitor_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor_digests')
    op.drop_table('monitor_subscribers')
    op.drop_table('monitor_snapshots')
    op.drop_table('monitor_resources')
    op.drop_table('monitor_entities')
    op.drop_table('monitor_topics')
    # ### end Alembic commands ###
